version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@npvwmiq0dlcmzlxr_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=BDFS_SUM2_PACIENTES
      - spring.datasource.password=ClaseFullStack1-
    restart: always